import type { Metadata } from 'next'
import './globals.css'
import { TheHeader } from '@/components/TheHeader'
import TheFooter from '@/components/TheFooter'
import { Providers } from '@/components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <TheHeader />
          <div className='container'>{children}</div>
          <TheFooter />
        </Providers>
      </body>
    </html>
  )
}
